### ISSUE TITLE
How do I add a circuit diagram or circuit link?

### ISSUE THREAD

**Issue by Strilanc** [errorcorrectionzoo/eczoo_data#299]
I have a [5,1,3] encoder with fewer two-qubit-gates than the referenced papers. How do I add it to the [5,1,3] page? Specifically, how do I add images and external URLs and code blocks?

![image](https://github.com/errorcorrectionzoo/eczoo_data/assets/79941/8b235616-6995-43eb-9e8e-5632f7cdcd31)

[Quirk link](https://algassert.com/quirk#circuit=%7B%22cols%22%3A%5B%5B1%2C1%2C1%2C1%2C1%2C1%2C%22H%22%5D%2C%5B%22X%22%2C1%2C1%2C1%2C1%2C1%2C%22%E2%80%A2%22%5D%2C%5B%22~rsgs%22%5D%2C%5B1%2C%22~599r%22%2C%22~599r%22%2C%22~599r%22%2C%22~599r%22%5D%2C%5B%22Y%22%2C1%2C%22H%22%2C%22H%22%2C%22H%22%5D%2C%5B1%2C1%2C%22%E2%80%A2%22%2C%22Z%22%5D%2C%5B%22%E2%80%A2%22%2C%22X%22%5D%2C%5B1%2C%22X%22%2C1%2C1%2C%22%E2%80%A2%22%5D%2C%5B1%2C%22X%22%2C1%2C%22%E2%80%A2%22%5D%2C%5B%22X%22%2C1%2C%22%E2%80%A2%22%5D%2C%5B%22Z%22%2C%22%E2%80%A2%22%5D%2C%5B%22X%22%2C1%2C1%2C%22%E2%80%A2%22%5D%2C%5B1%2C1%2C%22H%22%2C%22H%22%2C%22H%22%5D%2C%5B%22~e7sn%22%2C%22~e7sn%22%2C%22~e7sn%22%2C%22~e7sn%22%2C%22~e7sn%22%5D%2C%5B%22zpar%22%2C%22zpar%22%2C%22zpar%22%2C%22zpar%22%2C%22zpar%22%2C%220%22%2C%22zpar%22%5D%2C%5B%22xpar%22%2C%22xpar%22%2C%22xpar%22%2C%22xpar%22%2C%22xpar%22%2C%220%22%2C%22xpar%22%5D%2C%5B%22xpar%22%2C1%2C%22xpar%22%2C%22zpar%22%2C%22zpar%22%2C%220%22%5D%2C%5B%22zpar%22%2C%22xpar%22%2C1%2C%22xpar%22%2C%22zpar%22%2C%220%22%5D%2C%5B%22zpar%22%2C%22zpar%22%2C%22xpar%22%2C1%2C%22xpar%22%2C%220%22%5D%2C%5B%22xpar%22%2C%22zpar%22%2C%22zpar%22%2C%22xpar%22%2C1%2C%220%22%5D%5D%2C%22gates%22%3A%5B%7B%22id%22%3A%22~rsgs%22%2C%22name%22%3A%22in%22%2C%22matrix%22%3A%22%7B%7B1%2C0%7D%2C%7B0%2C1%7D%7D%22%7D%2C%7B%22id%22%3A%22~599r%22%2C%22name%22%3A%22%7C0%3E%22%2C%22matrix%22%3A%22%7B%7B1%2C0%7D%2C%7B0%2C1%7D%7D%22%7D%2C%7B%22id%22%3A%22~e7sn%22%2C%22name%22%3A%22out%22%2C%22matrix%22%3A%22%7B%7B1%2C0%7D%2C%7B0%2C1%7D%7D%22%7D%5D%7D)

```
import stim

print(stim.Circuit("""
    # Input: qubit 0
    # Output: A [5,1,3] code over qubits 0,1,2,3,4
    Y 0
    R 1 2 3 4
    H 2 3 4
    CZ 2 3
    CX 0 1 3 1 4 1
    CX 2 0
    CZ 0 1
    CX 3 0
    H 2 3 4
""").diagram())
```

```
q0: -Y---@-----X-@-X---
         |     | | |
q1: -R---X-X-X-|-@-|---
           | | |   |
q2: -R-H-@-|-|-@---|-H-
         | | |     |
q3: -R-H-@-@-|-----@-H-
             |
q4: -R-H-----@-------H-
```

There are also many highly symmetrical ZX graphs of the encoder (up to permutation and single qubit basis change of the outputs). Examples:

![image](https://github.com/errorcorrectionzoo/eczoo_data/assets/79941/173e33a5-4f54-4450-961b-9a115b455fee)

![image](https://github.com/errorcorrectionzoo/eczoo_data/assets/79941/8b1123ce-60a9-401d-89a1-d0d95f69e298)

Presumably there are ways to add linkable versions of these things, instead of just references to books and papers? Books and papers are great and all, but it's often difficult to find the specific figure and the representation is usually not computer parseable.

**Comment by valbert4** [comment]
Thanks for these ideas.
- Pictures can be added directly into the zoo; see [https://github.com/errorcorrectionzoo/eczoo_data/tree/main/codes/quantum/qubits/stabilizer/topological/surface/two_dim/surface](surface code folder) which has a picture in it that is then LaTeX-added inside the yml file.
- ZX diagrams and code blocks would need to be explained. We don't yet ZX calculus because I don't know where it's useful for QEC; I might have a summer student look into it. Since it applies to all qubit codes, you're welcome to jumpstart this and put in some explanation in say code_id:qubits_into_qubits. Alternatively, you can just link to these at this point either in the relevant section.
- We link to databases and tables all the time in the "notes" subsection of YML files. General links are done using \href{http://####}{text}. However, links should be to pages that are going to survive; we want to avoid dead links.

**Comment by Strilanc** [comment]
Thanks, that solves me questions.

> We don't yet ZX calculus because I don't know where it's useful for QEC

This is kind of a weird thing to hear as the reason to not use ZX. ZX is incredibly ridiculously useful for QEC. Here are a few examples of papers that fruitfully use the ZX calculus in some way, as part of researching or tooling for QEC circuits:

- https://arxiv.org/abs/1704.08670
- https://arxiv.org/abs/1812.01238
- https://arxiv.org/abs/2204.14038
- https://arxiv.org/abs/1903.10477
- https://arxiv.org/abs/1905.08916
- https://arxiv.org/abs/2109.01076
- https://arxiv.org/abs/2206.12780
- https://arxiv.org/abs/2211.15465
- https://arxiv.org/abs/2302.02192 (we ironically cut the ZX stuff from the final paper because it was just too long, but I assure you behind the scenes we used to heavily)
- https://arxiv.org/abs/2302.07395
- https://arxiv.org/abs/2303.08829

I literally use the ZX calculus every day as part of my own research. It is an incredibly useful bag of concepts and diagrams. Not using it would be like not using quantum circuits. For me the most useful things are the following:

- There's a 1:1 mapping between surface code lattice surgery spacetime diagrams and ZX graphs. Using this connection allows substantially more complicated spacetime diagrams to be built, reverse engineered, understood, verified, etc. You can also convert braiding of defects and anyons in the surface code into ZX diagrams, though there the connection is less direct since edges correspond to links between rings instead of pipes between junctions.
- ZX diagrams don't care about time ordering, so you can rotate them in spacetime to get new perspectives on the same construction. In quantum circuits, teleportation is surprising. In ZX, teleportation and gate teleportation and delayed choice and etc are all natural because they are related by rotations or simple rewrite rules.
- The stabilizer subset of the ZX calculus is efficient to evaluate and analyze. I have a janky tool for doing it that I wouldn't really recommend, but you can at least check it can compute the stabilizer flows of enormous diagrams faster than the computer draws frames: https://algassert.com/zigxag

**Comment by valbert4** [comment]
- Thanks, it was good to know this. I've peppered it many of those refs into the surface code entry, which is our most popular one. This should help make more people aware.

- Turns out I already had one ref where I wrote ZX-calculus with the dash; right now, it's written without. 

- Recent work could be of interest to you; it feels like ZX should be useful for such circuit codes: https://errorcorrectionzoo.org/c/spacetime_circuit
